# Generated by Django 2.0 on 2019-01-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_desc',
            field=models.CharField(default='', max_length=120, verbose_name='商品内容'),
        ),
    ]
